### ISSUE TITLE
Mismatching number of frames in original transcripts vs. BERT for GENEA Challenge

### ISSUE THREAD

**Issue by stefan-kohnen** [Svito-zar/gesticulator#4]
Hi!

I have cloned this repository and performed steps 1 and 2 from the README. I placed the files from folder `GENEA_Challenge_2020_data_release` into one directory per category instead of having two directories `Test_data` and `Training_data`. During step 2, when I run  `python process_dataset.py`, the following error occurs:
```
ERROR: The number of frames in the encoded transcript (4678)
       does not match the number of frames in the input (4762)!
```
The error comes from processing `Recording_004.json` in `Training_data/transcripts` with `parse_json_transcript.py`.

How can I fix this error?

I assume the error might have to do with the fact that I am using the transcriptions originally published for the GENEA challenge. I assume this because In an earlier commit, the README proposed to use the original dataset and transcribe it with Google ASR. But now it says to use the GENEA folder, so I wanted to give it a try.

Any info on this issue would help me out a great deal! Thanks in advance.

Cheers,
Stefan

**Comment by Svito-zar** [comment]
Hi @stefan-kohnen.

Thanks for flagging up your issue.

It should not be because you used the data from `GENEA_Challenge_2020_data_release`, this data is in fact the best data to use.
It could be because the code you forked contained a bug with was fixed in the last 11 commits.
Could you please merge the latest commits on your fork and try again?

If the error persist - I can investigate it.

Taras

**Comment by stefan-kohnen** [comment]
Hi, thank you for the quick answer.

I actually cloned your repository from scratch today because I saw the changes and hoped they would fix the error. So I'm using the latest version and the error persists.

**Comment by Svito-zar** [comment]
The issue comes from the fact that some JSON transcriptions are not ending with a dot as is expected by this code base.

We are going to fix it by the end of the week.

If would like to work with the code asap - adding a dot at the end of each transcription file should solve this issue.

**Comment by stefan-kohnen** [comment]
Thank you very much for looking into it.

**Comment by Svito-zar** [comment]
I could reproduce your error and fixed it with the help of @nagyrajmund.
Here is the commit with the updates we had to do: https://github.com/Svito-zar/gesticulator/commit/914c0a2ee6ac5736782b39c17177676d3de7bb00

It should work for you now. Please let me know if it does.

**Comment by stefan-kohnen** [comment]
Yes, it works now. Thank you @nagyrajmund and @Svito-zar 

@Svito-zar Concerning 914c0a2ee6ac5736782b39c17177676d3de7bb00 lines 17, 18 and 19 in `split_dataset.py`:
The indexes refer to the indexes found in `GENEA_Challenge_2020_data_release `'s subfolder `Training_Data`, right?

**Comment by Svito-zar** [comment]
Yes, that's correct. Those indexes are arbitrary and can be modified as you wish. 
[GENEA Challenge ](https://genea-workshop.github.io/2020/#gesture-generation-challenge) participants used the folder `Training_Data` for training and `Test_Data` for testing. 
We had a different split in our experiments which we unfortunately cannot share.
The results should not depend much on the data split.
